// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

public class SwenDeptInfo {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","WebDrivers/chromedriver.exe");
        driver = new ChromeDriver(new ChromeOptions());
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test() {

        //Land at Rit.edu
        driver.get("https://rit.edu/");
        driver.manage().window().setSize(new Dimension(1920, 1080));

        // Go into academics tab at top of page.
        WebElement academics = driver.findElement(By.xpath("//*[@id=\"main-nav--link--academics\"]"));
        academics.click();

        sleep(500);

        // Click on colleges section.
        WebElement colleges = driver.findElement(By.xpath("//*[@id=\"block-rit-bootstrap-subtheme-rit-main-menu\"]/ul/li[2]/div/div/ul[1]/li[5]/a"));
        colleges.click();

        sleep(4000);

        // Click on Golisano college of computing section.
        WebElement goli = driver.findElement(By.xpath("//*[@id=\"block-rit-bootstrap-subtheme-content\"]/div/div[3]/div[3]/div/div/div/div/div/div/div/div/ul/li[3]/a"));
        goli.click();

        sleep(500);

        // Click on Golisano college of computing [academics] section
        WebElement academics2 = driver.findElement(By.xpath("//*[@id=\"main-nav--link--academics\"]"));
        academics2.click();

        sleep(500);

        // Navigate to departments section
        WebElement departments = driver.findElement(By.xpath("//*[@id=\"block-rit-bootstrap-subtheme-rit-main-menu\"]/ul/li[2]/div/div/ul[2]/li[2]/a"));
        departments.click();

        sleep(500);

        // Navigate to departments section
        WebElement se = driver.findElement(By.xpath("//*[@id=\"block-rit-bootstrap-subtheme-content\"]/div/div[3]/div[1]/div/div/div/div/div/div/div/div/ul/li[4]/a"));
        se.click();

        sleep(500);
    }

    void sleep(int time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
