// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

public class TigerSearch {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","WebDrivers/chromedriver.exe");
    driver = new ChromeDriver(new ChromeOptions());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void useCase1() {

    // Test name: Use Case #1
    // Step # | name | target | value | comment
    // 1 | open | https://tigercenter.rit.edu/tigerCenterApp/landing |  | 
    driver.get("https://tigercenter.rit.edu/tigerCenterApp/landing");
    // 2 | setWindowSize | 1920x1080 |  | 
    driver.manage().window().setSize(new Dimension(1920, 1080));
    // 3 | click | css=.img-text:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".img-text:nth-child(2)")).click();
    // 4 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
    // 5 | type | css=.completer-input | Swen 352 |

      shleep(1000);

      driver.findElement(By.cssSelector(".completer-input")).sendKeys("Swen 352");
    // 6 | sendKeys | css=.completer-input | ${KEY_ENTER} | 
    driver.findElement(By.cssSelector(".completer-input")).sendKeys(Keys.ENTER);
    // 7 | click | css=.classSearchAdvancedSearchText |  |

      shleep(3000);

    driver.findElement(By.cssSelector(".classSearchAdvancedSearchText")).click();
    // 8 | select | xpath=//div/div/div[3]/div/select | label=RIT Main |
    {
      WebElement dropdown = driver.findElement(By.xpath("//div/div/div[3]/div/select"));
      dropdown.findElement(By.xpath("//option[. = 'RIT Main']")).click();
    }
    // 9 | mouseDownAt | css=.styledSelect > .ng-dirty | -513.25,-316.5 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".styledSelect > .ng-dirty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 10 | mouseMoveAt | css=.styledSelect > .ng-dirty | -513.25,-316.5 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".styledSelect > .ng-dirty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseUpAt | css=.styledSelect > .ng-dirty | -513.25,-316.5 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".styledSelect > .ng-dirty"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 12 | click | css=.styledSelect > .ng-dirty |  | 
    driver.findElement(By.cssSelector(".styledSelect > .ng-dirty")).click();
    // 13 | click | css=.col-xs-12:nth-child(6) .styledSelectWidthFix |  | 
    driver.findElement(By.cssSelector(".col-xs-12:nth-child(6) .styledSelectWidthFix")).click();
    // 14 | select | css=.col-xs-12:nth-child(6) .styledSelectWidthFix | label=Golisano Col Comp&Info Science | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".col-xs-12:nth-child(6) .styledSelectWidthFix"));
      dropdown.findElement(By.xpath("//option[. = 'Golisano Col Comp&Info Science']")).click();
    }
    // 15 | click | css=.col-xs-12:nth-child(6) .styledSelectWidthFix |  | 
    driver.findElement(By.cssSelector(".col-xs-12:nth-child(6) .styledSelectWidthFix")).click();
    // 16 | click | css=.col-xs-12:nth-child(8) .styledSelectWidthFix |  | 
    driver.findElement(By.cssSelector(".col-xs-12:nth-child(8) .styledSelectWidthFix")).click();
    // 17 | select | css=.col-xs-12:nth-child(8) .styledSelectWidthFix | label=Software Engineering | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".col-xs-12:nth-child(8) .styledSelectWidthFix"));
      dropdown.findElement(By.xpath("//option[. = 'Software Engineering']")).click();
    }
    // 18 | type | id=mat-input-0 | Mkaoer | 
    driver.findElement(By.id("mat-input-0")).sendKeys("Mkaoer");
    // 19 | sendKeys | id=mat-input-0 | ${KEY_ENTER} | 
    driver.findElement(By.id("mat-input-0")).sendKeys(Keys.ENTER);
    // 20 | click | css=.col-xs-12:nth-child(8) .styledSelectWidthFix |  | 
    driver.findElement(By.cssSelector(".col-xs-12:nth-child(8) .styledSelectWidthFix")).click();
    // 21 | click | css=.col-xs-12:nth-child(14) |  | 
    driver.findElement(By.cssSelector(".col-xs-12:nth-child(14)")).click();
    // 22 | mouseOver | css=.advancedSearchDoneButton |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".advancedSearchDoneButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | css=.advancedSearchDoneButton |  | 
    driver.findElement(By.cssSelector(".advancedSearchDoneButton")).click();
    // 24 | click | css=.classSearchAttrsWidthFix |  | 
    driver.findElement(By.cssSelector(".classSearchAttrsWidthFix")).click();
  }

  void shleep(int time) {
      try {
          Thread.sleep(time);
      } catch (InterruptedException e) {
          e.printStackTrace();
      }
  }
}
